/* @HEADER
 * @version 0.8.9 | 2026-05-11
 * @purpose Generate readable and machine-readable backlog views from structured work items
 * @sidecar backlog-sync.mjs.header.md
 * @layer tooling | @hex _none_ | @ctx _none_
 * @public false
 * @edit careful
 */

import { collectWorkItems, ensureWriteIfChanged, parseArgs, readText, result } from './_shared.mjs';
import { ValidationError } from '../lib/errors.mjs';

const args = parseArgs();
const wantJson = args.has('--json');
const checkOnly = args.has('--check');

const OUT_MD = 'docs/backlog/_generated/index.md';
const OUT_JSON = 'docs/backlog/_generated/backlog.json';

function renderMarkdown(items, generatedAt = new Date().toISOString()) {
  const groups = new Map();
  for (const item of items) {
    const key = item.status || 'draft';
    groups.set(key, [...(groups.get(key) || []), item]);
  }

  const lines = [
    '<!-- generated by scripts/checks/backlog-sync.mjs -->',
    '',
    '# Generated backlog',
    '',
    `Generated: ${generatedAt}`,
    '',
  ];

  for (const [status, statusItems] of groups.entries()) {
    lines.push(`## ${status}`, '');
    for (const item of statusItems) {
      lines.push(`- **${item.id}** — ${item.title} \`${item.type}\` module=\`${item.module_ref}\``);
      for (const criterion of item.acceptance) lines.push(`  - acceptance: ${criterion}`);
    }
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

function stripGeneratedLine(markdown) {
  return markdown.replace(/^Generated: .*\n/m, 'Generated: <stable>\n');
}

async function main() {
  const items = await collectWorkItems();
  const now = new Date().toISOString();
  const payload = { generatedAt: now, itemCount: items.length, items };

  const currentMd = await readText(OUT_MD).catch(() => null);
  const currentJson = await readText(OUT_JSON).catch(() => null);

  // Idempotency: compare substantive content without generatedAt
  let jsonChanged = true;
  if (currentJson) {
    try {
      const prev = JSON.parse(currentJson);
      const { generatedAt: _a, ...prevSub } = prev;
      const { generatedAt: _b, ...curSub } = payload;
      jsonChanged = JSON.stringify(prevSub) !== JSON.stringify(curSub);
    } catch { /* parse error → treat as changed */ }
  }
  if (!jsonChanged && currentJson) payload.generatedAt = JSON.parse(currentJson).generatedAt;
  const md = renderMarkdown(items, payload.generatedAt);
  const mdChanged = !currentMd || stripGeneratedLine(currentMd) !== stripGeneratedLine(md);
  const json = JSON.stringify(payload, null, 2) + '\n';
  const changed = mdChanged || jsonChanged;

  if (!checkOnly) {
    await ensureWriteIfChanged(OUT_MD, md);
    await ensureWriteIfChanged(OUT_JSON, json);
  }

  const errors =
    checkOnly && changed ? [new ValidationError('Generated backlog is out of date')] : [];
  const output = result('backlog-sync', errors.length === 0, errors, [], {
    markdownFile: OUT_MD,
    jsonFile: OUT_JSON,
    changed,
  });

  if (wantJson) {
    console.log(JSON.stringify(output, null, 2));
    process.exit(output.ok ? 0 : 1);
  }
  if (!output.ok) {
    console.error(errors[0]?.message ?? output.errors[0]);
    process.exit(1);
  }
  console.log(`${checkOnly ? 'checked' : 'wrote'} generated backlog`);
}

main().catch((error) => {
  const output = result('backlog-sync', false, [
    error instanceof Error ? error.message : String(error),
  ]);
  if (wantJson) console.log(JSON.stringify(output, null, 2));
  else console.error(output.errors[0]);
  process.exit(1);
});
